routes/backend.php
<?php
//Backend



Route::group(['prefix' => 'system','middleware'=>['bindings','auth','role','log','permission:'.basename(request()->path())]], function () {
    Route::get('log/pages/Exception-logs', '\Rap2hpoutre\LaravelLogViewer\LogViewerController@index');
  Route::group(['namespace' => 'Admin' ], function () {

      Route::get('/home','home\homeController@index');
      Route::resource('log', 'log\logController');
      Route::resource('user', 'user\usersController');
      Route::resource('role', 'user\rolesController');
      Route::get('LogViewer','log\LogViewerController@index');
      Route::get('password/updatepassword','password\passwordController@index');
      Route::get('/user/password/{id}','user\usersController@password');
      Route::post('/user/update_password/{id}','user\usersController@updatepassword');
      Route::get('/user/change_password/{id}','password\passwordController@change_password');
      Route::post('/user/change_password/{id}','password\passwordController@updatepassword');
      Route::post('/change_language','config\settingsController@store');
      Route::resource('leads', 'leads\LeadsController');
      Route::resource('clients', 'clients\ClientsController');
      Route::resource('addresses', 'addresses\AddressesController');
      Route::resource('tech_levels', 'configs\TechLevelsController');
      Route::resource('project_phases', 'configs\ProjectPhasesController');
      Route::resource('project_tasks', 'project_tasks\ProjectTasksController');
//      Route::group(['middleware' => 'checkAuthorizedDealsBroker' ], function () {
          Route::resource('deals', 'deals\DealsController');
          Route::resource('proposals', 'proposals\ProposalsController');
          Route::resource('projects', 'projects\ProjectsController');
          Route::resource('project_equipments', 'project_equipments\ProjectEquipmentsController');
          Route::resource('project_technicians', 'project_technicians\ProjectTechniciansController');
//      });
      Route::resource('technicians', 'technicians\TechniciansController');
      Route::resource('dispatch', 'dispatch\DispatchController');
      Route::resource('timesheet', 'timesheet\TimesheetController');
      Route::post('/timesheet/save', 'timesheet\TimesheetController@UpdateTimeSheet');

      Route::resource('phases', 'phases\PhasesController');
      Route::resource('ajax_handler', 'ajax_handler\AjaxHandlerController');
      //Route::get('ajax_handler', 'ajax_handler\AjaxHandlerController');
//      Route::get('projects/phases', function (){
//          dd("sdfwrwe");
//      });


//      Route::get('{module}/pages/{page}', Request::segment(4) . 'Controller@index')->middleware('permission:'.Request::segment(4));
//
//      Route::get('{module}', Request::segment(2) . 'Controller@index')->middleware('permission:'.Request::segment(2));
//
//      Route::get('{module}/{page}', Request::segment(2) . 'Controller@' . Request::segment(3))->middleware('permission:'.Request::segment(2));
//
//      Route::post('{module}/{page}', Request::segment(2) . 'Controller@' . Request::segment(3))->middleware('permission:'.Request::segment(2));
//
//      Route::get('{module}/{page}/{id}', Request::segment(2) . 'Controller@' . Request::segment(3))->middleware('permission:'.Request::segment(2));
//
//      Route::get('{module}/pages/{page}/{id}', Request::segment(4) . 'Controller@' . Request::segment(5))->middleware('permission:'.Request::segment(4));
//
//      Route::post('{module}/pages/{page}/{id}', Request::segment(4) . 'Controller@' . Request::segment(5))->middleware('permission:'.Request::segment(4));
//
//      Route::get('{module}/pages/{page}/{abc}/{id}', Request::segment(4) . 'Controller@' . Request::segment(5))->middleware('permission:'.Request::segment(4));
//
//      Route::post('{module}/pages/{page}/{abc}/{id}', Request::segment(4) . 'Controller@' . Request::segment(5))->middleware('permission:'.Request::segment(4));


  });

});

routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| This file is where you may define all of the routes that are handled
| by your application. Just tell Laravel the URIs it should respond
| to using a Closure or controller method. Build something great!
|
*/
define("PREFIX", env('PREFIX','system'));
define("PAGINATION", env('PAGINATION',20));
Route::get('lang/{lang}', ['as'=>'lang.switch', 'uses'=>'LanguageController@switchLang']);
Route::get('/',function(){
    return view('welcome');
});

Route::get('system','Auth\LoginController@showLoginForm');
Route::get('/','Auth\LoginController@showLoginForm');
Route::get('/login','Auth\LoginController@showLoginForm');
Route::get('/system/login','Auth\LoginController@showLoginForm');
Route::post('/system/login','Auth\LoginController@login')->middleware(['throttle:5','log']);
Route::get('/system/logout','Auth\LoginController@logout');


include('backend.php');


// Auth::routes();

app/ProjectTechnicians.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class ProjectTechnicians extends Model
{
    protected $table = "cs_project_technicians";
    protected $guarded = ['id', '_token'];

    protected $fillable = ['task_id','total_hour','project_id','cost','date','technician_id'];
    protected $perPage = 30;

    public function getAllData($project_id,$task_id,$keyword = null){

        $data = $this->where("project_id","=",$project_id)->where("task_id","=",$task_id);
        if($keyword != null){
            $keyword = trim($keyword);
            $data->where(function($query) use ($keyword){
                $query
                    ->orWhere("title","LIKE","%$keyword%")
                    ->orWhere("cost","LIKE","%$keyword%");
            });
        }

//        if($taskFilter != null){
//            $taskFilter = trim($taskFilter);
//            $data->where("task_id","=",$taskFilter);
//        }

        return $data->orderBy("created_at","DESC")->paginate($this->perPage);
    }

    public function getDataById($id){

    }

    public function addData($dataArray){
        return $this->create($dataArray);
    }

    public function updateData($dataArray,$id){

        return $this->find($id)->update($dataArray);
    }

    public function deleteData($id){
        return $this->find($id)->delete();
    }

    public  function technician(){
        return $this->belongsTo("App\Technician","technician_id","id");
    }
}

app/Http/Controllers/Admin/project_technicians/ProjectTechniciansController.php
<?php

namespace App\Http\Controllers\Admin\project_technicians;

use App\Http\Requests\ProjectTechniciansRequest;
use App\ProjectTechnicians;
use App\Technician;
use App\Permission;
use App\User;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Input;


class ProjectTechniciansController extends Controller
{

    public function __construct(User $users,Permission $permisionModel,ProjectTechnicians $projectTech,Technician $technician)
    {
        $this->pageTitle = "Project Technicians";
        $this->model = $projectTech;
        $this->users = $users;
        $this->technician = $technician;
        $this->permisionModel = $permisionModel;
        $this->redirectUrl = PREFIX."/project_technicians";
        $this->respectiveProjectUrl = PREFIX."/projects";
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        if(!Input::has('project_id') || !Input::has('task_id')){
            return redirect($this->respectiveProjectUrl)->withErrors(["alert-danger" => "Invalid URL access."]);
        }

        $datas["pageTitle"] = $this->pageTitle;
        $datas["formURL"] = $this->redirectUrl;
        $datas["data"] = $this->model->getAllData(Input::get('project_id'),Input::get('task_id'),Input::get('keywords'));
        return view('backend.project_technicians.index',$datas);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $data["routeName"] = $this->redirectUrl;
        $data["redirectBackURL"] = $this->redirectUrl;
        $data["pageTitle"] = $this->pageTitle;
        $project_id = Input::get("project_id");
        $task_id = Input::get("task_id");
        $techOnTask = $this->model->where("project_id","=",$project_id)->where("task_id","=",$task_id)->pluck("technician_id")->toArray();

        $technicians =$this->technician->whereNotIn("id",$techOnTask)->get();
        $techArr = ["" => "none"];
        foreach ($technicians as $key =>$technician){
            $techArr[$technician->id] = $technician->name." (level:".$technician->TechLevel->title.", cost:".$technician->TechLevel->cost.")";

        }
        $data["technician"] = $techArr;

        return view('backend.project_technicians.create',$data);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(ProjectTechniciansRequest $projectTechReq)
    {
        //dd($projectTechReq->all());
        //try{
            $this->model->addData($projectTechReq->all());
            return redirect($this->redirectUrl."?project_id=".$projectTechReq->get("project_id")."&task_id=".Input::get('task_id'))->withErrors(["alert-success" => "Successfully added Technician."]);
//        }catch (\Exception $e){
//            return redirect()->back()->withErrors(["alert-danger" => "An error Ocurred."]);
//        }

    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id )
    {
        //dump($techLvl);
        $project_id = Input::get("project_id");
        $task_id = Input::get("task_id");
        //$project_equipment = ProjectTechnicians::findOrFail($id);
        //$project_technician = ProjectTechnicians::where("project_id","=",$project_id)->where("task_id","=",$task_id)->first();
        $project_technician = ProjectTechnicians::find($id);
        if($project_technician == null){
            return redirect()->back()->withErrors(["alert-danger" => "The Data doesn't exists on our record."]);
        }

        $project_id = Input::get("project_id");
        $task_id = Input::get("task_id");
        $techOnTask = $this->model->where("project_id","!=",$project_id)->where("task_id","!=",$task_id)->pluck("technician_id")->toArray();

        $technicians =$this->technician->whereIn("id",$techOnTask)->orWhereIn("id",[$project_technician->technician_id])->get();

        $techArr = ["" => "none"];
        foreach ($technicians as $key =>$technician){
            $techArr[$technician->id] = $technician->name." (level:".$technician->TechLevel->title.", cost:".$technician->TechLevel->cost.")";

        }
        $data["technician"] = $techArr;



        //dd($data);
        //dd($project_technician);
        $data["pageTitle"] = $this->pageTitle;
        $data["routeName"] = "project_technicians.update";
        $data["redirectBackURL"] = $this->redirectUrl;
        return view('backend.project_technicians.edit',$data,compact('project_technician'));
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(ProjectTechniciansRequest $projectTechReq, $id)
    {
        try{
            $this->model->updateData($projectTechReq->all(),$id);
            return redirect($this->redirectUrl."?project_id=".$projectTechReq->get("project_id")."&task_id=".Input::get('task_id'))->withErrors(["alert-success" => "Successfully edited Technician."]);
        }catch (\Exception $e){
            return redirect()->back()->withErrors(["alert-danger" => "An error Ocurred."]);
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        try{
            $this->model->deleteData($id);
            return redirect()->back()->withErrors(["alert-success" => "Successfully removed Technician."]);
        }catch (\Exception $e){
            return redirect()->back()->withErrors(["alert-danger" => "An error Ocurred."]);
        }
    }
}

resources/views/backend/project_technicians/create.blade.php
@extends('backend.master')

@section('title', trans('Add New Technician'))

@section('content')

<div id="page-title">
        <h2 style="display:inline-block">Add Technician</h2>
        <div class="clearfix"></div>
</div>

<div class="breadcrumb-section clearfix">
  <ol class="breadcrumb">
    <li><a href="{{URL::to(PREFIX.'/home')}}">Home</a></li>
      <li class="active"><a href="{{URL::to(PREFIX.'/projects')}}" >{{"Project Management"}}</a></li>
      <li><a href="{{ URL::route('projects.show',Input::get("project_id")) }}" >Project Details</a></li>
      <li><a href="{{URL::route('project_technicians.index',["project_id" => Input::get('project_id'),"task_id" => Input::get('task_id')])}}" >Project Technicians</a></li>
    <li class="active"><a href="Javascript::void();" >Add Technician</a></li>
  </ol>
</div>

@include('errors/errors')

{!!Form::open(['method'=>'POST','url'=>$routeName, 'class'=>'form-horizontal bordered-row'])!!}
<div class="panel">
  <div class="panel-body">
      {!! Form::hidden("project_id",Input::get('project_id')) !!}
      {!! Form::hidden("task_id",Input::get('task_id')) !!}
      @include('backend.project_technicians.includes.form',['btnTxt'=>'Save'])


      <div class="clearfix"></div>

    </div>
</div>


{!!Form::close() !!}
@stop

@section('scripts')

<style>
.form-horizontal .control-label{
text-align:left;
}
</style>

@stop

resources/views/backend/project_technicians/edit.blade.php
@extends('backend.master')

@section('title', trans('Edit Project Technician'))

@section('content')

    <div id="page-title">
        <h2 style="display:inline-block">Edit Project Technician</h2>
        <div class="clearfix"></div>
    </div>

    <div class="breadcrumb-section clearfix">
        <ol class="breadcrumb">
            <li><a href="{{URL::to(PREFIX.'/home')}}">Home</a></li>
            <li class="active"><a href="{{URL::to(PREFIX.'/projects')}}" >{{"Project Management"}}</a></li>
            <li><a href="{{ URL::route('projects.show',Input::get("project_id")) }}" >Project Details</a></li>
            <li><a href="{{URL::route('project_technicians.index',["project_id" => Input::get('project_id'),"task_id" => Input::get('task_id')])}}" >Project Technicians</a></li>
            <li class="active"><a href="Javascript::void();" >Edit Project Technician</a></li>
        </ol>
    </div>

    @include('errors/errors')

    <div class="panel">
        <div class="panel-body">

            {!!Form::model($project_technician,['method'=>'PUT','route'=>[$routeName,$project_technician->id], 'class'=>'form-horizontal bordered-row'])!!}
                {!! Form::hidden("id",null) !!}
            {!! Form::hidden("project_id",Input::get('project_id')) !!}
            {!! Form::hidden("task_id",Input::get('task_id')) !!}
                @include('backend.project_technicians.includes.form',['btnTxt'=>'Update'])
            {!!Form::close() !!}
            <div class="clearfix"></div>

        </div>
    </div>

@stop

@section('scripts')

    <style>
        .form-horizontal .control-label{
            text-align:left;
        }
    </style>

@stop

resources/views/backend/project_technicians/index.blade.php
@extends('backend.master')
@section('title',trans($pageTitle))
@section('content')



<div id="page-title">
    <h2 style="display:inline-block">{{$pageTitle}}</h2>
    <div class="right" style="float:right">
        @if(Auth::user()->canDo('project_technicians.project_technicians.create'))
            <a class="btn btn-primary" href="{{URL::route('project_technicians.create',["project_id" => Input::get('project_id'),"task_id" => Input::get('task_id')])}}"><i class="glyph-icon icon-plus" style="margin-right:10px;"></i>Add New</a>
        @endif
    </div>
</div>

<div class="breadcrumb-section clearfix">
  <ol class="breadcrumb">
    <li><a href="{{URL::to(PREFIX.'/home')}}">Home</a></li>
      <li class="active"><a href="{{URL::to(PREFIX.'/projects')}}" >{{"Project Management"}}</a></li>
      <li><a href="{{ URL::route('projects.show',Input::get("project_id")) }}" >Project Details</a></li>
    <li class="active"><a href="Javascript::void();" >{{$pageTitle}}</a></li>
  </ol>
</div>

@include('errors.errors')

<div class="panel">
  <div class="panel-body">
    {{--{!!Form::open(['method'=>'GET','url'=>$formURL, 'class'=>'form-horizontal'])!!}--}}
      {{--<div class="form-group">--}}

        {{--<div class="col-sm-3"></div>--}}
        {{--<div class="col-md-4"></div>--}}
        {{--<label class="col-sm-2 control-label">Search</label>--}}
          {{--<div class="col-md-3">--}}
            {{--<div class="input-group">--}}

                {{--<input type="text" class="form-control" name="keywords" value="{{Input::get('keywords')}}" autocomplete="off">--}}
                {{--<input type="hidden" class="form-control" name="project_id" value="{{Input::get('project_id')}}" autocomplete="off">--}}
                {{--<input type="hidden" class="form-control" name="task_id" value="{{Input::get('task_id')}}" autocomplete="off">--}}
                {{--<span class="input-group-btn">--}}
                    {{--<button class="btn btn-primary" type="submit">Go !</button>--}}
                {{--</span>--}}

            {{--</div>--}}
          {{--</div>--}}
      {{--</div>--}}
    {{--{!!Form::close() !!}--}}





    <div class="example-box-wrapper">
      <div class="scroll-columns">
        <table class="table table-bordered table-striped table-condensed cf" data-toggle="dataTable" data-form="deleteForm">
          <thead class="cf">
            <tr>
                <th>S.N.</th>
                <th>Technician</th>
                @if(Auth::user()->canDo('project_technicians.project_technicians.destroy'))
                <th>Action</th>
                    @endif
            </tr>
          </thead>
          <tbody>
          @if($data->isEmpty())
              <tr>

                  <td class="no-data" colspan="6">
                      <b>No data to display!</b>
                  </td>
              </tr>
          @else
          @php  $a=$data->perPage() * ($data->currentPage()-1); @endphp
            @foreach($data as $d)
                @if($d->technician != null)
                @php $a++ @endphp
            <tr>
                <td>{{ $a }}</td>
                <td>{{$d->technician->name}}</td>


                <td>
                    @if(Auth::user()->canDo('project_technicians.project_technicians.destroy'))
                        {!! Form::model($d, ['method' => 'delete', 'route' => ['project_technicians.destroy', $d->id], 'class' =>'form-inline form-delete']) !!}
                        {!! Form::hidden('id', $d->id) !!}
                        <button type="submit" name="delete_modal" class="btn btn-round btn-sm btn-danger" ><i class="glyphicon glyphicon-trash"></i> Delete </button>
                        {!! Form::close() !!}
                    @endif

                    @if(Auth::user()->canDo('project_technicians.project_technicians.edit'))

                        <a href="{{ URL::to(PREFIX.'/project_technicians/'.$d->id.'/edit?project_id='.Input::get("project_id").'&task_id='.Input::get("task_id")) }}"  class="btn btn-round btn-sm btn-info" ><i class="glyphicon glyphicon-edit"></i> Edit </a>
                    @endif

                </td>

            </tr>
                @endif
            @endforeach
              @endif
          </tbody>
        </table>
      </div>
    </div>
      @if(!$data->isEmpty())
          <div class="pagination-tile"> <label class="pagination-sub">Showing {{($data->currentpage()-1)*$data->perpage()+1}} to {{(($data->currentpage()-1)*$data->perpage())+$data->count()}} of {{$data->total()}} entries</label>
              <ul class="pagination" style="float:right ; margin:0px;">
                  {!! str_replace('/?', '?',$data->appends(['keywords'=>Input::get('keywords')])->render()) !!}

              </ul>
          </div>
      @endif
      <div class="clearfix"></div>

</div>
</div>

@stop

@section('scripts')

<link rel="stylesheet" type="text/css" href="{{URL::asset('backend/widgets/input-switch/inputswitch.css')}}">

<script type="text/javascript" src="{{URL::asset('backend/widgets/input-switch/inputswitch.js')}}"></script>
<script type="text/javascript">
/* Input switch */

$(function() { "use strict";
    $('.input-switch').bootstrapSwitch();
});




</script>

@stop